### ISSUE TITLE
Implement way for potential users to be notified when this is live

### ISSUE THREAD

**Issue by NunoSempere** [dspytdao/Algo_AMM#32]
Hi, I'd be interested in knowing when this is live, but it looks like it's pretty early right now. Thoughts on having a form somewhere so that users can be notified when this goes live?

Best,
Nuño

**Comment by Pfed-prog** [comment]
sure, this a very interesting issue, we definitely need to implement an email list :)

**Comment by Pfed-prog** [comment]
@NunoSempere closing this, because we created a twitter account and going live very soon https://twitter.com/AlgoAmm
